services:
  - type: web
    name: socios-club-online
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false
      - key: MAILCHIMP_API_KEY
        sync: false
      - key: MAILCHIMP_SERVER_PREFIX
        sync: false
      - key: MAILCHIMP_AUDIENCE_ID
        sync: false
      - key: GOOGLE_DRIVE_CLIENT_EMAIL
        sync: false
      - key: GOOGLE_DRIVE_PRIVATE_KEY
        sync: false
      - key: GOOGLE_DRIVE_FOLDER_ID
        sync: false
